# Generated by Django 3.2.3 on 2021-05-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_communityanswer_question_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityQuestion',
        ),
    ]
