# Generated by Django 3.2.3 on 2021-05-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_delete_communityquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityanswer',
            name='answer_assets',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
