# Generated by Django 3.2.3 on 2021-05-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_communityanswer_answer_assets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityAnswer',
        ),
    ]
