# Generated by Django 3.2.3 on 2021-05-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('community', '0005_delete_communityanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_description', models.TextField()),
                ('publishing_date', models.DateField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.signup')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_discrption', models.TextField()),
                ('answer_assets', models.FileField(null=True, upload_to='')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.communityquestion')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.signup')),
            ],
        ),
    ]
