# Generated by Django 3.2.3 on 2021-05-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_alter_communityquestion_stu_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityquestion',
            name='stu_name',
            field=models.CharField(default='mnnit', max_length=255, null=True),
        ),
    ]
