# Generated by Django 3.2.3 on 2021-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_alter_communityanswer_answer_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityanswer',
            name='answer_assets',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
