# Generated by Django 3.2.3 on 2021-05-19 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0002_alter_signup_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTransaction',
            fields=[
                ('d', models.CharField(max_length=255)),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.signup')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('d', models.CharField(max_length=255)),
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.signup')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.chattransaction')),
            ],
        ),
    ]
