# Generated by Django 3.2.3 on 2021-05-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattransaction',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
