# Generated by Django 3.2.3 on 2021-05-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chattransaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
