# Generated by Django 3.2.3 on 2021-05-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('student_id', models.CharField(max_length=10, unique=True, verbose_name='College Registration ID')),
                ('email', models.EmailField(max_length=100, verbose_name='College Email ID')),
                ('course', models.CharField(max_length=20, verbose_name='Course Name')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('dob', models.DateField(max_length=10, verbose_name='Date Of Birth')),
                ('photo', models.BinaryField(verbose_name='Photo')),
                ('mobile_number', models.IntegerField(verbose_name='mobile number')),
            ],
        ),
    ]
