# Generated by Django 3.2.3 on 2021-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Photo'),
        ),
    ]
