# Generated by Django 3.2.3 on 2021-05-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='lost_date',
            field=models.DateField(),
        ),
    ]
