# Generated by Django 3.2.3 on 2021-05-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfi', '0002_alter_lostitem_lost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='lost_date',
            field=models.DateField(),
        ),
    ]
