# Generated by Django 3.2.3 on 2021-05-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfi', '0003_alter_founditem_lost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founditem',
            old_name='lost_date',
            new_name='found_date',
        ),
        migrations.RenameField(
            model_name='founditem',
            old_name='lost_place',
            new_name='found_place',
        ),
        migrations.RenameField(
            model_name='founditem',
            old_name='lost_time',
            new_name='found_time',
        ),
    ]
