# Generated by Django 3.2.3 on 2021-05-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfi', '0004_auto_20210522_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='item_pic1',
            field=models.ImageField(blank=True, null=True, upload_to='found/images/', verbose_name='pic1'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_pic1',
            field=models.ImageField(blank=True, null=True, upload_to='lost/images/', verbose_name='pic1'),
        ),
    ]
