# Generated by Django 3.2.3 on 2021-05-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfi', '0004_auto_20210522_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='match',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
