# Generated by Django 3.2.3 on 2021-05-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfi', '0005_matching_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching',
            name='match',
        ),
    ]
