# Generated by Django 3.1 on 2021-05-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfi', '0005_auto_20210522_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
