# Generated by Django 3.2.3 on 2021-05-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfi', '0005_auto_20210522_1312'),
        ('lfi', '0006_remove_matching_match'),
    ]

    operations = [
    ]
