# Generated by Django 3.2.3 on 2021-05-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfi', '0006_auto_20210522_1804'),
        ('lfi', '0006_remove_matching_match'),
    ]

    operations = [
    ]
